# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: thetolkienblack
  description: Role for installing Kibana
  company: Graylock
  license: MIT
  min_ansible_version: "2.8"
  galaxy_tags:
    - monitoring
    - kibana
    - alerting
dependencies:
  - common
  - core
  - elasticsearch
