Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.box_version = "4.3.12"
  config.vm.disk :disk, size: "10GB", primary: true

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1

    libvirt.storage_pool_name = "vagrant-pool"
    libvirt.default_prefix = "dns_vagrant"
    libvirt.storage :file, :size => '10G'

  end

  # Set the hostname
  config.vm.hostname = "dns.graylock.eu"

  # Configure the network to use DHCP
  config.vm.network "public_network", 
    bridge: "br0", 
    dev: "br0",
    type: "bridge"

  # Define a new NFS mount (e.g., /mnt/my_nfs)
  config.vm.synced_folder "/media/sidney/NAS/Homelab/", "/mnt/data"

  # Provisioning with shell script
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y openssh-server ansible nfs-common resolvconf
    systemctl enable ssh
    systemctl restart ssh

    # Force eth1 to use DHCP
    echo "auto eth1" >> /etc/network/interfaces
    echo "iface eth1 inet dhcp" >> /etc/network/interfaces
    systemctl restart networking

    mkdir -p /home/vagrant/.ssh
    echo "#{File.read(File.expand_path('~/.ssh/id_ed25519.pub'))}" >> /home/vagrant/.ssh/authorized_keys
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant /home/vagrant/.ssh

    # Set DNS servers manually
    echo "nameserver 192.168.50.54" > /etc/resolv.conf
    echo "nameserver 192.168.50.1" >> /etc/resolv.conf
    echo "nameserver 45.90.28.252" >> /etc/resolv.conf
  SHELL
end
