# defaults file for install_cockpit
core_redis_memory_usage: 256mb

# UFW rules for Cockpit
core_cockpit_ufw_rules:
  - { port: "9090", proto: 'tcp', comment: 'Cockpit web UI' }
  - { port: "3265", proto: 'udp', comment: 'dnsmasq service' }
  - { port: "9898", proto: 'tcp', comment: 'Cockpit websocket' }
  - { port: "6379", proto: 'tcp', comment: 'redis service' }

core_cockpit_apparmor_profiles:
  - { profile: "usr.bin.redis-server", template: "redis-apparmor.j2" }
  - { profile: "usr.sbin.dnsmasq", template: "dnsmasq-apparmor.j2" }
  - { profile: "usr.lib.cockpit.cockpit-ws", template: "cockpit-apparmor.j2" }

core_cockpit_services:
#  - redis
#  - dnsmasq
  - cockpit.socket

core_cockpit_aa_exec:
  - /usr/lib/cockpit/cockpit-ws
  - /usr/lib/cockpit/cockpit-session
#  - /usr/bin/dnsmasq
#  - /usr/bin/redis-server

core_cockpit_aa_profiles:
  - /etc/apparmor.d/usr.bin.redis-server
  - /etc/apparmor.d/usr.sbin.dnsmasq
  - /etc/apparmor.d/usr.lib.cockpit.cockpit-ws
  - /etc/apparmor.d/usr.lib.cockpit.cockpit-session
