---
- name: Install bouncers inside container
  ansible.builtin.shell: |
    docker exec {{ crowdsec_docker_container_name }} cscli bouncers install {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ crowdsec_docker_bouncers }}"
  loop_control:
    label: "{{ item }}"