---
- name: Install parsers inside container
  ansible.builtin.shell: |
    docker exec {{ crowdsec_docker_container_name }} cscli parsers install {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ crowdsec_docker_parsers }}"
  loop_control:
    label: "{{ item }}"