# SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: 'Core | Include Starship tasks'
  ansible.builtin.include_tasks: "starship/main.yml"
  when:
    - core_install_starship is defined
    - core_install_starship

- name: 'Core | Include Security tasks'
  ansible.builtin.include_tasks: "security/main.yml"

- name: 'Core | Include Archive tasks'
  ansible.builtin.include_tasks: "archive_tools/main.yml"

- name: 'Core | Include Diagnostic tasks'
  ansible.builtin.include_tasks: "diagnostic_tools/main.yml"
  when:
    - core_install_diagnostic_tools is defined
    - core_install_diagnostic_tools

- name: 'Core | Include Network tasks'
  ansible.builtin.include_tasks: "network_tools/main.yml"
  when:
    - core_install_network_tools is defined
    - core_install_network_tools

- name: 'Core | Include Cockpit tasks'
  ansible.builtin.include_tasks: "cockpit/main.yml"
  when:
    - core_install_cockpit is defined
    - core_install_cockpit

- name: 'Core | Include Nvidia tasks'
  ansible.builtin.include_tasks: "nvidia/main.yml"
  when:
    - core_install_nvidia is defined
    - core_install_nvidia
    - has_nvidia_gpu
