---
- name: 'Restart dnsmasq'
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
  become: true

- name: 'Restart cockpit'
  ansible.builtin.service:
    name: cockpit
    state: restarted
  become: true

- name: 'Restart redis'
  ansible.builtin.service:
    name: redis-server
    state: restarted
  become: true
