# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: 'Development Tools | Include OpenJDK tasks'
  ansible.builtin.include_tasks: "openjdk/main.yml"
  when: development_tools_install_openjdk

- name: 'Development Tools | Include NodeJS tasks'
  ansible.builtin.include_tasks: "nodejs/main.yml"
  when: development_tools_install_nodejs

- name: 'Development Tools | Include Python tasks'
  ansible.builtin.include_tasks: "python/main.yml"
  when: development_tools_install_python
