# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_init
- name: 'Development Tools | OpenJDK | Include OpenJDK vars'
  ansible.builtin.include_vars: "openjdk/main.yml"

- name: 'Development Tools | OpenJDK | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'Development Tools | OpenJDK | Clone jenv repository'
  ansible.builtin.git:
    repo: https://github.com/jenv/jenv.git
    dest: /home/{{ ansible_user }}/.jenv
    update: true
    version: master
  become: false
  become_user: "{{ ansible_user }}"

- name: 'Development Tools | OpenJDK | Add jenv initialization to .bashrc'
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: |
      # jenv initialization
      export PATH="$HOME/.jenv/bin:$PATH"
      eval "$(jenv init -)"
    insertafter: EOF
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: 'Development Tools | OpenJDK | Ensure jenv is initialized for the user'
  ansible.builtin.shell: |
    export PATH="$HOME/.jenv/bin:$PATH" && eval "$(jenv init -)" && jenv doctor
  become: false
  become_user: "{{ ansible_user }}"
  environment:
    PATH: "/home/{{ ansible_user }}/.jenv/bin:{{ ansible_env.PATH }}"
  args:
    creates: /home/{{ ansible_user }}/.jenv/version
