---
- name: 'Hashicorp | Debian | Install HashiCorp packages (Terraform, Vault, Consul, Nomad, Packer)'
  ansible.builtin.apt:
    name:
      - terraform
      - vault
      - consul
      - nomad
      - packer
    state: present
    update_cache: true
  become: true
