- name: Download HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp-archive-keyring.gpg
    mode: "0644"
  become: true

- name: Dearmor HashiCorp GPG key
  ansible.builtin.command:
    cmd: gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/hashicorp-archive-keyring.gpg --import /tmp/hashicorp-archive-keyring.gpg
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true

- name: Set correct permissions on the GPG key
  ansible.builtin.file:
    path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: "0644"
  become: true

- name: Add hashicorp.list with custom template
  ansible.builtin.template:
    src: hashicorp.list.j2
    dest: /etc/apt/sources.list.d/hashicorp.list
    owner: root
    group: root
    mode: "0644"
  notify: Update apt cache
  become: true

- name: Install HashiCorp packages (Terraform, Vault, Consul, Nomad, Packer)
  ansible.builtin.apt:
    name:
      - terraform
      - vault
      - consul
      - nomad
      - packer
    state: present
    update_cache: true
  become: true
