# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_init
- name: 'Hashicorp | Debian | Download HashiCorp GPG key'
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp-archive-keyring.gpg
    mode: "0644"
  become: true

- name: 'Hashicorp | Debian | Dearmor HashiCorp GPG key'
  ansible.builtin.command:
    cmd: gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/hashicorp-archive-keyring.gpg --import /tmp/hashicorp-archive-keyring.gpg
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true

- name: 'Hashicorp | Debian | Set correct permissions on the GPG key'
  ansible.builtin.file:
    path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: "0644"
  become: true

- name: 'Hashicorp | Debian | Add hashicorp.list with custom template'
  ansible.builtin.template:
    src: hashicorp.list.j2
    dest: /etc/apt/sources.list.d/hashicorp.list
    owner: root
    group: root
    mode: "0644"
  notify: Update apt cache
  become: true

- name: 'Hashicorp | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
