---
- name: Include Starship handlers
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/starship/main.yml"

- name: Include Cockpit handlers
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/cockpit/main.yml"

- name: Include Nvidia handlers
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/nvidia/main.yml"
