---
- name: 'Include Starship handlers'
  ansible.builtin.import_tasks: "starship/main.yml"

- name: 'Include Cockpit handlers'
  ansible.builtin.import_tasks: "cockpit/main.yml"

- name: 'Include Nvidia handlers'
  ansible.builtin.import_tasks: "nvidia/main.yml"

- name: 'Include Security handlers'
  ansible.builtin.import_tasks: "security/main.yml"
