---
- name: 'Core | Security | Debian | AppArmor | Install AppArmor packages'
  ansible.builtin.apt:
    name:
      - apparmor
      - apparmor-utils
      - apparmor-profiles
      - apparmor-profiles-extra
    state: present
    update_cache: true
  become: true

- name: 'Core | Security | Debian | AppArmor | Check if AppArmor binary exists'
  ansible.builtin.stat:
    path: /usr/sbin/aa-status
  register: apparmor_binary

- name: 'Core | Security | Debian | AppArmor | Check if AppArmor is installed'
  ansible.builtin.stat:
    path: /etc/apparmor.d
  register: apparmor_dir
  become: true
  when: apparmor_binary.stat.exists

- name: 'Core | Security | Debian | AppArmor | Set Apparmor is installed'
  ansible.builtin.set_fact:
    apparmor_installed: apparmor_binary.stat.exists and apparmor_dir.stat.exists and apparmor_dir.stat.isdir
  changed_when: false
  failed_when: false

- name: 'Core | Security | Debian | AppArmor | Ensure AppArmor service is enabled and started'
  ansible.builtin.systemd:
    name: apparmor
    state: started
    enabled: true
  register: apparmor_started
  become: true
  when: apparmor_installed

- name: 'Core | Security | Debian | AppArmor | Update kernel boot parameters for AppArmor'
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((?!apparmor=1|security=apparmor).)*"$'
    line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} apparmor=1 security=apparmor"'
    backrefs: true
  become: true
  notify: Update grub

- name: 'Core | Security | Create systemd abstraction for apparmor'
  ansible.builtin.template:
    src: security/systemd_abstraction.apparmor.j2
    dest: /etc/apparmor.d/abstractions/systemd
    owner: root
    group: root
    mode: '0644'
  become: true
  when:
    - apparmor_installed is defined
    - apparmor_installed

- name: 'Core | Security | Create hostname abstraction for apparmor'
  ansible.builtin.template:
    src: security/hostname_abstraction.apparmor.j2
    dest: /etc/apparmor.d/abstractions/hostname
    owner: root
    group: root
    mode: '0644'
  become: true
  when:
    - apparmor_installed is defined
    - apparmor_installed

- name: 'Core | Security | Create net abstraction for apparmor'
  ansible.builtin.template:
    src: security/net_abstraction.apparmor.j2
    dest: /etc/apparmor.d/abstractions/net
    owner: root
    group: root
    mode: '0644'
  become: true
  when:
    - apparmor_installed is defined
    - apparmor_installed