# SPDX-License-Identifier: MIT-0
---
# handlers file for ansible_role_template
- name: 'Restart OpenSearch'
  ansible.builtin.systemd:
    name: opensearch
    state: restarted
    enabled: true
  become: true
