# SPDX-License-Identifier: MIT-0
---
- name: Restart OpenSearch
  ansible.builtin.systemd:
    name: opensearch
    state: restarted
    enabled: true
  become: true

- name: Include OS-specific handlers
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
