# SPDX-License-Identifier: MIT-0
---
containers_install_podman: false
containers_install_docker: true
containers_docker_ports:
  - port: 2375
    proto: tcp
    comment: Docker API (unencrypted)
  - port: 2376
    proto: tcp
    comment: Docker API (encrypted)
