---
- name: Ensure Graylog prerequisite packages are installed
  ansible.builtin.apt:
    name:
      - uuid-runtime
      - pwgen
    state: present
    update_cache: true
  become: true

- name: Add OpenSearch GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
    state: present
  become: true

- name: Add OpenSearch repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.opensearch.org/releases/bundles/opensearch/{{ opensearch_repo_version }}/debian/ stable main"
    state: present
  become: true
  notify: Update apt cache

- name: Ensure OpenSearch is installed
  ansible.builtin.apt:
    name: opensearch
    state: present
  environment:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_admin_password }}"
  become: true
