---
- name: Ensure Graylog prerequisite packages are installed
  ansible.builtin.apt:
    name:
      - uuid-runtime
      - pwgen
    state: present
    update_cache: true
  become: true

- name: Download Opensearch GPG key
  ansible.builtin.get_url:
    url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
    dest: /tmp/opensearch-key.gpg
    mode: '0644'
  become: true

- name: Import OpenSearch GPG key
  ansible.builtin.command:
    cmd: gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/opensearch.gpg --import /tmp/opensearch-key.gpg
    creates: /usr/share/keyrings/opensearch.gpg
  become: true

- name: Set permissions for OpenSearch GPG keyring
  ansible.builtin.file:
    path: /usr/share/keyrings/opensearch.gpg
    mode: '0644'
  become: true

- name: Copy opensearch repository template
  ansible.builtin.template:
    src: opensearch.repo.j2
    dest: /etc/apt/sources.list.d/opensearch.list
    owner: root
    group: root
    mode: '0644'
  become: true


- name: Ensure OpenSearch is installed
  ansible.builtin.apt:
    name: opensearch
    state: present
  environment:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_admin_password }}"
  become: true
  update-cache: true
