# SPDX-License-Identifier: MIT-0
---
# Opensearch
opensearch_host: "0.0.0.0"
opensearch_initial_master_nodes: "['']"
opensearch_http_port: 9200
opensearch_data_path: "/var/lib/opensearch"
opensearch_logs_path: "/var/log/opensearch"
opensearch_cluster_name: "opensearch-cluster"
opensearch_node_name: "node-1"
opensearch_discovery_type: "single-node"
opensearch_admin_username: admin
opensearch_admin_password: "{{ lookup('password', '/dev/null', length=20, chars='ascii_letters,digits') }}"
opensearch_max_map_count: 262144
opensearch_nofile_ulimit: 65536
