# SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == debian_family_name

- name: Get list of task files from security directory
  ansible.builtin.find:
    paths: "{{ role_path }}/tasks/security"
    patterns: "*.yml"
  register: security_tasks

- name: Include all security task files
  ansible.builtin.include_tasks: "{{ item.path }}"
  loop: "{{ security_tasks.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Ensure ansible_user variable is defined
  ansible.builtin.fail:
    msg: "The variable 'ansible_user' is not defined. Please provide it in your inventory or playbook."
  when: ansible_user is not defined

- name: Copy bashrc file
  ansible.builtin.template:
    src: bashrc.j2
    dest: /home/{{ ansible_user }}/.bashrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: false

- name: Set Bash as the default shell for the user
  ansible.builtin.command:
    cmd: chsh -s /bin/bash {{ ansible_user }}
  changed_when: ansible_env.SHELL != '/bin/bash'

- name: Ensure commands use bash shell
  ansible.builtin.shell:
    cmd: echo "Default shell set to bash"
  args:
    executable: /bin/bash
  changed_when: false
