# SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: 'Common | Ensure ansible_user variable is defined'
  ansible.builtin.fail:
    msg: "The variable 'ansible_user' is not defined. Please provide it in your inventory or playbook."
  when: ansible_user is not defined

- name: 'Common | Include OS-based tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'Common | Set Bash as the default shell for the user'
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "{{ default_shell | default('/bin/bash') }}"
  register: shell_change
  when: ansible_env.SHELL != (default_shell | default('/bin/bash'))
  notify: Ensure commands use bash shell

- name: 'Common | Set variables based on system environments'
  ansible.builtin.set_fact:
    shell_name: "{{ ansible_env.SHELL | basename }}"
    user_shell: "{{ ansible_env.SHELL }}"
    home_dir: "{{ ansible_env.HOME }}"
    is_bash: "{{ ansible_env.SHELL }} == '/bin/bash'"

- name: 'Common | Copy bashrc file'
  ansible.builtin.template:
    src: "{{ shell_name }}rc.j2"
    dest: "{{ home_dir }}/.{{ shell_name }}rc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become_user: "{{ ansible_user }}"

- name: 'Common | Ensure /etc/localtime is world-readable'
  ansible.builtin.file:
    path: /etc/localtime
    mode: '0644'
    owner: root
    group: root
  become: true

- name: 'Common | Ensure /usr/lib/ssl/openssl.cnf is world-readable'
  ansible.builtin.file:
    path: /usr/lib/ssl/openssl.cnf
    mode: '0644'
    owner: root
    group: root
  become: true

