# SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure ansible_user variable is defined
  ansible.builtin.fail:
    msg: "The variable 'ansible_user' is not defined. Please provide it in your inventory or playbook."
  when: ansible_user is not defined

- name: Copy bashrc file
  ansible.builtin.copy:
    src: bashrc.j2
    dest: /home/{{ ansible_user }}/.bashrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
