# SPDX-License-Identifier: MIT-0
---
# graylog defaults
graylog_repo_version: "graylog-6.1-repository_latest"
graylog_port: 12201
graylog_datanode_http_port: 12202
graylog_is_master_node: true
graylog_master_node_server: "192.168.50.1:12201"
graylog_http_external_uri: "https://graylog.graylock.eu"
graylog_trusted_proxies: ""
graylog_mongodb_uri: "mongodb://{{ gl_mongo_username }}:{{ gl_mongo_password }}@{{ ansible_hostname }}:27017/graylog"
graylog_transport_email_enabled: true
graylog_prometheus_exporter_enabled: true
graylog_prometheus_exporter_bind_address: "127.0.0.1:9833"
