---
- name: 'Virtualization | Libvirt | Storage | Create storage directory'
  ansible.builtin.file:
    path: /mnt/storage/vagrant
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: 'Virtualization | Libvirt | Storage | Create libvirt storage pool'
  ansible.builtin.command: >
    virsh pool-define-as --name {{ virtualization_libvirt_storage_pool_name }} --type dir
    --target {{ libvirt_storage_pool_path }}
  register: pool_define
  changed_when: "'Pool already exists' not in pool_define.stdout"
  failed_when: "'Pool already exists' not in pool_define.stdout"
  when: virtualization_libvirt_storage_pool_name is defined and libvirt_storage_pool_path is defined

- name: 'Virtualization | Libvirt | Storage | Build storage pool'
  ansible.builtin.command: virsh pool-build {{ virtualization_libvirt_storage_pool_name }}
  register: pool_build
  changed_when: "'Pool already exists' not in pool_build.stdout"
  failed_when: "'Pool already exists' not in pool_build.stdout"
  when: virtualization_libvirt_storage_pool_name is defined and libvirt_storage_pool_path is defined

- name: 'Virtualization | Libvirt | Storage | Start storage pool'
  ansible.builtin.command: virsh pool-start {{ virtualization_libvirt_storage_pool_name }}
  register: pool_start
  changed_when: "'Pool already exists' not in pool_start.stdout"
  failed_when: "'Pool already exists' not in pool_start.stdout"
  when: virtualization_libvirt_storage_pool_name is defined and libvirt_storage_pool_path is defined

- name: 'Virtualization | Libvirt | Storage | Autostart storage pool'
  ansible.builtin.command: virsh pool-autostart {{ virtualization_libvirt_storage_pool_name }}
  register: pool_autostart
  changed_when: "'Pool already exists' not in pool_autostart.stdout"
  failed_when: "'Pool already exists' not in pool_autostart.stdout"
  when: virtualization_libvirt_storage_pool_name is defined and libvirt_storage_pool_path is defined
