# SPDX-License-Identifier: MIT-0
---
# tasks file for virt_tools
- name: Include Libvirt tasks
  ansible.builtin.include_vars: "{{ role_path }}/vars/libvirt.yml"

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Check if libvirt is installed
  ansible.builtin.command: dpkg -l | grep libvirt-daemon-system
  register: libvirt_installed
  changed_when: false

- name: Check if virsh is installed
  ansible.builtin.command: which virsh
  register: virsh_installed
  changed_when: false
  when: libvirt_installed.rc == 0

- name: Configure UFW rules for libvirt and QEMU
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ libvirt_ufw_rules }}"
  become: true
  when:
    - ufw_installed.rc == 0
    - virsh_installed.rc == 0
  notify: Reload UFW

- name: Include Libvirt setup tasks
  ansible.builtin.include_tasks: "libvirt_vm_setup.yml"
  when: libvirt_installed.rc == 0

- name: Include Libvirt network tasks
  ansible.builtin.include_tasks: "libvirt_network_setup.yml"
  when: libvirt_installed.rc == 0

- name: Include Libvirt Vagrant Storage tasks
  ansible.builtin.include_tasks: "libvirt_vagrant_storage_pool.yml"
  when: libvirt_installed.rc == 0
