# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: Check if Podman is installed
  ansible.builtin.stat:
    path: /usr/bin/podman
  register: podman_binary

- name: Check if Docker is installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_binary

- name: Include Podman tasks
  ansible.builtin.include_tasks: "podman/main.yml"
  when:
    - install_podman
    - not podman_binary.stat.exists

- name: Include Docker tasks
  ansible.builtin.include_tasks: "docker/main.yml"
  when:
    - install_docker
    - not docker_binary.stat.exists
