- name: Install Cockpit and related packages
  ansible.builtin.apt:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-bridge
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
    state: present
    update_cache: true
  become: true

- name: Configure dnsmasq to run on port 3265
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: "^port="
    line: "port=3265"
    create: true
    owner: root
    group: root
    mode: "0644"
  notify: Restart dnsmasq

- name: Limit Redis memory usage to 256MB
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "^maxmemory "
    line: "maxmemory 256mb"
    create: true
    owner: root
    group: root
    mode: "0644"
  notify: Restart redis

- name: Ensure dnsmasq service is running
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true

- name: Ensure cockpit service is running
  ansible.builtin.service:
    name: cockpit
    state: started
    enabled: true

- name: Ensure Redis service is running
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true
