# SPDX-License-Identifier: MIT-0
---
# tasks file for install_cockpit
- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == debian_family_name

- name: Restart Cockpit service after AppArmor profile changes
  ansible.builtin.service:
    name: cockpit
    state: restarted
  become: true
  when:
    - apparmor_dir.stat.exists
    - apparmor_dir.stat.isdir

- name: Ensure dnsmasq service is running
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
  become: true

- name: Ensure cockpit service is running
  ansible.builtin.service:
    name: cockpit
    state: started
    enabled: true
  become: true

- name: Ensure Redis service is running
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true
  become: true
