- name: Install OpenJDK
  ansible.builtin.apt:
    name:
      - openjdk-{{ openjdk_version }}-jdk
      - openjdk-{{ openjdk_version }}-jre
    state: present
    update_cache: true
  become: true

- name: Ensure ansible_user variable is defined
  ansible.builtin.fail:
    msg: "The variable 'ansible_user' is not defined. Please provide it in your inventory or playbook."
  when: ansible_user is not defined

- name: Install jenv dependencies
  ansible.builtin.apt:
    name:
      - git
      - curl
    state: present
    update_cache: true
  become: true

- name: Install jenv dependencies
  ansible.builtin.apt:
    name:
      - git
      - curl
    state: present
    update_cache: true
  become: true
