---
- name: 'Common | Handlers | Debian | Update apt cache'
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: 'Common | Handlers | Debian | Upgrade apt packages'
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  become: true
