- name: Check if Cockpit AppArmor profile is enabled
  ansible.builtin.command: aa-status
  register: aa_status
  changed_when: false

- name: Create AppArmor profiles from templates
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "/etc/apparmor.d/{{ item.profile }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ cockpit_apparmor_profiles }}"
  loop_control:
    label: "{{ item.profile }}"
  become: true
  notify:
    - Load multiple custom AppArmor profiles
    - Restart cockpit
    - Restart dnsmasq
    - Restart redis
  vars:
    apparmor_custom_profile: "{{ cockpit_apparmor_profiles }}"
  when:
    - apparmor_dir.stat.exists
    - apparmor_dir.stat.isdir
    - item.profile not in aa_status.stdout
