ansible_become: true
ansible_become_method: sudo
bridge_name: "br0"
kde_user: sidney
install_vagrant: false
install_lxc: false
install_lxd: false
ansible_ssh_private_key_file: ~/.ssh/graylock_ed25519
host_ipv4_addr: 192.168.50.54
host_ipv4_gw: 192.168.50.1
default_dns:
  - '192.168.50.54'
  - '{{ host_ipv4_gw }}'
  - '45.90.28.252'
  - '1.1.1.1'
host_bridge_name: br0
host_network_interface: enp14s0
timezone: Europe/Sofia
ssh_key_source: ~/.ssh/id_rsa.pub
ansible_host_dir: ~/Developer/home-automation/ansible
docker_registry: docker.io
default_shell: "/bin/bash"
default_gid: 0
default_uid: 0
apparmor_enforce_mode: false

# Smtp
smtp_server: smtp.gmail.com
smtp_port: 587
smtp_use_auth: true
smtp_from: default
smtp_use_tls: true
smtp_to: default
