# roles/qemu/tasks/debian.yml
---
- name: 'Grafana | Debian | Install Python crypto libraries'
  ansible.builtin.apt:
    name:
      - python3-cryptography
      - python3-openssl
    state: present
  become: true

- name: 'Grafana | Debian | Add Grafana GPG Key'
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: 'Grafana | Debian | Add Grafana APT repository'
  ansible.builtin.apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    filename: grafana

- name: 'Grafana | Debian | Install Grafana'
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true
