# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: 'Falco | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'Falco | Ensure Falco service is enabled and started'
  ansible.builtin.service:
    name: falco
    state: started
    enabled: true
  become: yes
