---
- name: 'ElasticSearch | Certs | Ensure certs directory exists'
  ansible.builtin.file:
    path: '{{ elasticsearch_certs_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: 'ElasticSearch | Certs | Generate CA private key (only if not exists)'
  community.crypto.openssl_privatekey:
    path: '{{ elasticsearch_certs_path }}/ca.key'
  become: true
  when: not lookup('ansible.builtin.file', elasticsearch_certs_path + '/ca.key', errors='ignore')

- name: 'ElasticSearch | Certs | Generate CA certificate (only if not exists)'
  community.crypto.x509_certificate:
    path: '{{ elasticsearch_certs_path }}/ca.crt'
    privatekey_path: '{{ elasticsearch_certs_path }}/ca.key'
    provider: selfsigned
    selfsigned_not_after: +3650d
  become: true
  when: not lookup('ansible.builtin.file', elasticsearch_certs_path + '/ca.crt', errors='ignore')

- name: 'ElasticSearch | Certs | Generate Elasticsearch private key'
  community.crypto.openssl_privatekey:
    path: '{{ elasticsearch_certs_path }}/elasticsearch.key'
  become: true

- name: 'ElasticSearch | Certs | Generate Elasticsearch CSR'
  community.crypto.openssl_csr:
    path: '{{ elasticsearch_certs_path }}/elasticsearch.csr'
    privatekey_path: '{{ elasticsearch_certs_path }}/elasticsearch.key'
    common_name: 'elasticsearch'
  become: true

- name: 'ElasticSearch | Certs | Sign Elasticsearch certificate'
  community.crypto.x509_certificate:
    path: '{{ elasticsearch_certs_path }}/elasticsearch.crt'
    csr_path: '{{ elasticsearch_certs_path }}/elasticsearch.csr'
    ownca_path: '{{ elasticsearch_certs_path }}/ca.crt'
    ownca_privatekey_path: '{{ elasticsearch_certs_path }}/ca.key'
    provider: ownca
    ownca_not_after: '+3650d'
  become: true
