# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: 'ElasticSearch | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'ElasticSearch | Generate Elasticsearch certificates'
  ansible.builtin.include_tasks: "certs.yml"

- name: 'ElasticSearch | Configure Elasticsearch'
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0640'
  become: true
  notify: Restart Elasticsearch

- name: 'ElasticSearch | Ensure Elasticsearch service is enabled and started'
  ansible.builtin.service:
    name: elasticsearch
    enabled: true
    state: started
  become: true
