- name: Create fail2ban jail.local from template
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart fail2ban

- name: Ensure Fail2ban service is enabled and started
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
  become: true
