---
- name: Configure UFW defaults
  community.general.ufw:
    default: "{{ item.policy }}"
    direction: "{{ item.direction }}"
  with_items:
    - { policy: 'deny', direction: 'incoming' }
    - { policy: 'allow', direction: 'outgoing' }
  become: true

- name: Allow SSH through UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: true
