# SPDX-License-Identifier: MIT-0
---
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ compose_file_dir }}"
    - "{{ container_data_dir }}"

- name: Write docker-compose files for each service
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_file_dir }}/{{ item.key }}.yml"
    mode: '0644'
  loop: "{{ compose_files | dict2items }}"
  notify: Restart docker service

- name: Launch docker-compose projects
  community.docker.docker_compose:
    project_src: "{{ compose_file_dir }}"
    files:
      - "{{ item.key }}.yml"
    state: present
    restarted: true
    restarted_force: true
    remove_orphans: true
    build: false
    pull: true
    recreate: smart
    services: []
    restarted_services: []
    detached: true
  loop: "{{ compose_files | dict2items }}"
