- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - dkms
      - build-essential
      - linux-headers-{{ ansible_kernel }}
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  state: present
  update_cache: true

- name: Enable i386 architecture (needed for some NVIDIA components)
  ansible.builtin.command: dpkg --add-architecture i386
  args:
    creates: /etc/dpkg/dpkg.cfg.d/multiarch
  notify: Update apt cache

- name: Install NVIDIA Driver (non-free)
  ansible.builtin.apt:
    name:
      - nvidia-driver
      - nvidia-kernel-dkms
      - nvidia-kernel-support
      - nvidia-vulkan-icd
      - libnvidia-glcore
      - nvidia-settings
      - nvidia-xconfig
    state: present
    update_cache: true

- name: Try loading NVIDIA module
  ansible.builtin.command: modprobe nvidia
  register: modprobe_result
  failed_when: false
  changed_when: false

- name: Check if /dev/nvidia0 exists
  ansible.builtin.stat:
  path: /dev/nvidia0
  register: nvidia_device

- name: Display warning if NVIDIA device is missing
  ansible.builtin.debug:
    msg: >
      NVIDIA device nodes not found. Kernel module may not be loaded or
      DKMS build may have failed. Reboot might be required.
  when: nvidia_device is defined and not nvidia_device.stat.exists

- name: Reboot if NVIDIA device node is missing
  ansible.builtin.reboot:
  when: nvidia_device is defined and not nvidia_device.stat.exists
