#SPDX-License-Identifier: MIT-0
---
# handlers file for install_cockpit
- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Restart cockpit
  ansible.builtin.service:
    name: cockpit
    state: restarted
