---
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true

- name: Reload UFW
  community.general.ufw:
    state: reloaded
  become: true
  changed_when: false

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}/apparmor.yml"
  when: ansible_os_family == debian_family_name
