#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: thetolkienblack
  description: This role installs the Cockpit web-based interface for servers.
  company: Graylock

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  galaxy_tags:
    - cockpit
    - web
    - server
    - interface
    - management

dependencies:
  - role: common