- name: Install system tools
  ansible.builtin.apt:
    name:
      - s-tui
      - smem
      - tcpdump
      - python3
      - python3-pip
      - python3-venv
      - htop
    state: present
    update_cache: true
  become: true

- name: Check if AppArmor is installed
  ansible.builtin.stat:
    path: /etc/apparmor.d
  register: apparmor_dir
  become: true

- name: Check if UFW is installed
  ansible.builtin.command:
    cmd: dpkg -s ufw
  register: ufw_installed
  changed_when: false
  failed_when: false
  become: true

# AppArmor profiles for diagnostic tools that need it
- name: Create AppArmor profile for tcpdump
  ansible.builtin.template:
    src: tcpdump-apparmor.j2
    dest: /etc/apparmor.d/usr.sbin.tcpdump
    owner: root
    group: root
    mode: '0644'
  become: true
  when:
    - apparmor_dir.stat.exists
    - apparmor_dir.stat.isdir
  notify: Reload AppArmor profiles

# UFW rules for diagnostic tools that need network access
- name: Allow necessary network access for diagnostic tools
  community.general.ufw:
    rule: allow
    direction: out
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  with_items:
    - { proto: 'tcp', port: '443' }  # HTTPS for tools that check for updates
    - { proto: 'udp', port: '53' }   # DNS for name resolution
  become: true
  when: ufw_installed.rc == 0
