- name: Install system tools
  ansible.builtin.apt:
    name:
      - s-tui
      - smem
      - tcpdump
      - python3
      - python3-pip
      - python3-venv
      - htop
    state: present
    update_cache: true
