- name: 'Core | Cockpit | Debian | Install Cockpit and related packages'
  ansible.builtin.apt:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-bridge
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
    state: present
    update_cache: true
  become: true
