---
- name: 'Core | Cockpit | DNSMASQ | Check if dnsmasq is configured with the correct port'
  ansible.builtin.command: grep -q '^port={{ dnsmasq_port }}' /etc/dnsmasq.conf
  register: dnsmasq_port_output
  changed_when: false
  failed_when: false

- name: 'Core | Cockpit | DNSMASQ | Configure dnsmasq to run on port 3265'
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: "^port="
    line: "port={{ dnsmasq_port }}"
    create: true
    owner: root
    group: root
    mode: "0644"
  notify: Restart dnsmasq
  become: true
  when: dnsmasq_port_output.rc != 0

- name: 'Core | Cockpit | DNSMASQ | Ensure dnsmasq service is running'
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
  become: true
