# SPDX-License-Identifier: MIT-0
---
# tasks file for install_cockpit
- name: 'Core | Cockpit | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'Core | Cockpit | Include Redis tasks'
  ansible.builtin.include_tasks: "redis.yml"

- name: 'Core | Cockpit | Include DNSMasq tasks'
  ansible.builtin.include_tasks: "dnsmasq.yml"

- name: 'Core | Cockpit | Include UFW tasks'
  ansible.builtin.include_tasks: "security/ufw.yml"

- name: 'Core | Cockpit | Enable and start multiple systemd services'
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ core_cockpit_services }}"
  become: true

- name: 'Core | Cockpit | Configure UFW rules for Cockpit and related services'
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ core_cockpit_ufw_rules }}"
  become: true
  when: ufw_installed
  notify:
    - Reload UFW
    - Restart cockpit
    - Restart dnsmasq
    - Restart redis

- name: 'Core | Cockpit | Create AppArmor profiles from templates'
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "/etc/apparmor.d/{{ item.profile }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ core_cockpit_apparmor_profiles }}"
  loop_control:
    label: "{{ item.profile }}"
  become: true
  notify:
    - Load multiple custom AppArmor profiles
    - Restart cockpit
    - Restart dnsmasq
    - Restart redis
  when:
    - apparmor_installed is defined
    - apparmor_installed
    - item.profile not in aa_status.stdout
