# SPDX-License-Identifier: MIT-0
---
- name: 'Core | Cockpit | Include cockpit vars'
  ansible.builtin.include_vars: "{{ role_path }}/vars/cockpit/main.yml"

# tasks file for install_cockpit
- name: 'Core | Cockpit | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

#- name: 'Core | Cockpit | Include Redis tasks'
#  ansible.builtin.include_tasks: "redis.yml"
#
#- name: 'Core | Cockpit | Include DNSMasq tasks'
#  ansible.builtin.include_tasks: "dnsmasq.yml"

- name: 'Core | Cockpit | Include Apparmor tasks'
  ansible.builtin.include_tasks: "apparmor.yml"

- name: 'Core | Cockpit | Enable and start multiple systemd services'
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ core_cockpit_services }}"
  become: true

- name: 'Core | Cockpit | Configure UFW rules for Cockpit and related services'
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ core_cockpit_ufw_rules }}"
  become: true
  when: ufw_installed
  notify:
    - Reload UFW
    - Restart cockpit
#    - Restart dnsmasq
#    - Restart redis
