---
virtualization_disk_size: 10GB
virtualization_ram_memory: 1024
virtualization_cpu_cores: 1
virtualization_storage_pool_name: default
virtualization_storage_default_prefix: vagrant
virtualization_vm_name: alpine
virtualization_vm_hostname: alpine
virtualization_network_name: public_network
virtualization_bridge_interface: "{{ host_bridge_name }}"
virtualization_synced_host_folder_dir: /mnt/data
virtualization_synced_guest_folder_dir: /mnt/data
virtualization_host_ssh_file: "{{ ssh_key_source }}"
virtualization_nameservers: "{{ default_dns }}"
