# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: thetokienblack
  description: Role to configure Podman containers on Debian-based systems.
  company: Graylock

  license: MIT

  min_ansible_version: "2.9"

  galaxy_tags:
    - podman
    - containers
    - debian
    - automation
    - nvidia
    - cockpit

dependencies:
  - role: common
  - role: cockpit
  - role: nvidia_drivers
