# SPDX-License-Identifier: MIT-0
---
- name: 'Core | Diagnostic | Load networking defaults'
  ansible.builtin.include_vars: "{{ role_path }}/vars/security.yml"

- name: 'Core | Diagnostic | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
