# SPDX-License-Identifier: MIT-0
---
- name: Load networking defaults
  ansible.builtin.include_vars: "{{ role_path }}/vars/security.yml"

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Include Redhat-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == redhat_family_name
