---
- name: Ensure the storage pool is created
  ansible.builtin.command:
    cmd: "virsh pool-info {{ virtualization_storage_pool_name }}"
  register: storage_pool_check
  failed_when: storage_pool_check.rc not in [0, 1]
  changed_when: storage_pool_check.rc == 1
  ignore_errors: true

- name: Create the storage pool if it does not exist
  ansible.builtin.command:
    cmd: "virsh pool-create-as {{ virtualization_storage_pool_name }} dir --target /var/lib/libvirt/pools/{{ virtualization_storage_pool_name }}"
  when: storage_pool_check.rc == 1
  changed_when: true

- name: Ensure the storage prefix directory exists
  ansible.builtin.file:
    path: "/var/lib/libvirt/pools/{{ virtualization_storage_pool_name }}/{{ virtualization_storage_default_prefix }}"
    state: directory
    mode: '0755'

- name: Copy the Vagrant template and replace placeholders
  ansible.builtin.template:
    src: vagrant.libvirt.alpine.j2
    dest: "{{ ansible_os_family | lower }}/{{ virtualization_vm_name }}/Vagrantfile"
    user: "{{ vm_username }}"
    group: "{{ vm_username }}"
    mode: '0644'

- name: Start the Vagrant VM
  ansible.builtin.command:
    cmd: vagrant up
  args:
    chdir: "{{ ansible_os_family | lower }}/{{ virtualization_vm_name }}"
  changed_when: false
