---
- name: Install the basic requirements
  hosts: all
  vars_files:
    - ../group_vars/all/vars.yml

  tasks:
    - name: Add non-free and contrib repositories
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free non-free-firmware"
        create: true
        owner: root
        group: root
        mode: '0644'

    - name: Update package cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - atool
          - openssh-server
          - p7zip
          - p7zip-full
          - unzip
          - rar
          - vim-nox
          - vim-common
          - iptables
          - iputils-ping
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
          - bash-completion
          - locales
          - cron
          - plocate
        state: present
        update_cache: true

    - name: Install system tools
      ansible.builtin.apt:
        name:
          - curl
          - gnupg2
          - wget
          - openssl
          - openssh-client
          - s-tui
          - smem
          - tcpdump
          - python3
          - python3-pip
          - python3-venv
          - htop
        state: present
        update_cache: true
