- hosts: all
  vars_files:
    - ../group_vars/all/vars.yml
  tasks: 
    - name: Update package cache
      ansible.builtin.apt: 
        update_cache: yes
    - name: Upgrade packages
      ansible.builtin.apt: 
        upgrade: dist
    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - atool
          - openssh-server
          - p7zip
          - p7zip-full
          - unzip
          - unrar
          - vim-nox
          - vim-common
          - iptables
          - iputils-ping
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
          - bash-completion
          - locales
          - cron
          - plocate
        state: present
        update_cache: yes
    - name: Install system tools
      ansible.builtin.apt:
        name:
          - curl
          - gnupg2
          - wget
          - openssl
          - openssh-client
          - s-tui
          - smem
          - tcpdump
          - python3
          - python3-pip
          - python3-venv
          - htop
        state: present
        update_cache: yes
    
