- name: Install Development Tools
  hosts: all
  vars_files:
    - ../group_vars/all/vars.yml
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install base dev tools
      ansible.builtin.apt:
        name:
          - fonts-firacode
          - graphviz
          - nmap
          - libvirt
          - vagrant
          - vagrant-libvirt
          - wireshark
          - dnsutils
          - speedtest-cli
          - jq
          - git
          - openjdk-17-jdk
          - nodejs
          - npm
          - software-properties-common
        state: present
        update_cache: true

    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download HashiCorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /tmp/hashicorp-archive-keyring.gpg
        mode: '0644'

    - name: Dearmor HashiCorp GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Set correct permissions on the GPG key
      ansible.builtin.file:
        path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        mode: '0644'

    - name: Add HashiCorp APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp
        install_python_apt: true


    - name: Install HashiCorp packages (Terraform, Vault, Consul, Nomad, Packer)
      ansible.builtin.apt:
        name:
          - terraform
          - vault
          - consul
          - nomad
          - packer
        state: present
