- name: Install NVIDIA Drivers and Container Toolkit
  hosts: all
  tasks:
    - name: Update and upgrade system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - dkms
          - build-essential
          - linux-headers-{{ ansible_kernel }}
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add the non-free and contrib repositories for Debian
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} non-free contrib"
        state: present

    - name: Enable i386 architecture (needed for some NVIDIA components)
      ansible.builtin.command: dpkg --add-architecture i386
      args:
        creates: /etc/dpkg/dpkg.cfg.d/multiarch

    - name: Update package lists after adding repos
      ansible.builtin.apt:
        update_cache: true

    - name: Install NVIDIA Driver (non-free)
      ansible.builtin.apt:
        name:
          - nvidia-driver
          - nvidia-kernel-dkms
          - nvidia-kernel-support
          - nvidia-vulkan-icd
          - libnvidia-glcore
          - nvidia-settings
          - nvidia-xconfig
        state: present

    - name: Install NVIDIA kernel modesetting
      ansible.builtin.apt:
        name:
          - nvidia-kernel-dkms
          - nvidia-modeset
        state: present

    - name: Verify NVIDIA kernel module is loaded
      ansible.builtin.command: modprobe nvidia
      register: modprobe_result
      changed_when: false
      ignore_errors: true

    - name: Add NVIDIA Docker repository GPG key
      ansible.builtin.get_url:
        url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
        dest: /etc/apt/keyrings/nvidia-container-runtime-keyring.gpg
        mode: '0644'

    - name: Add NVIDIA Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nvidia-container-runtime-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(lsb_release -cs) /"
        state: present
        filename: nvidia-container-runtime

    - name: Update package lists after adding NVIDIA Container repo
      ansible.builtin.apt:
        update_cache: true

    - name: Install NVIDIA Container Toolkit
      ansible.builtin.apt:
        name:
          - nvidia-container-toolkit
          - nvidia-container-runtime
        state: present

    - name: Configure Docker to use NVIDIA as the default runtime
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "runtimes": {
              "nvidia": {
                "path": "nvidia-container-runtime",
                "runtimeArgs": []
              }
            }
          }
        mode: '0644'
      notify: Restart Docker

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
