---
- name: 'Mongodb | Debian | Download MongoDB GPG key'
  ansible.builtin.get_url:
    url: https://pgp.mongodb.com/server-{{ mongodb_repo_version }}.asc
    dest: /tmp/mongodb-server-{{ mongodb_repo_version }}.asc
    mode: '0644'
  become: true

- name: 'Mongodb | Debian | Convert MongoDB GPG key to dearmored format'
  ansible.builtin.command: >
    gpg --dearmor -o /usr/share/keyrings/mongodb-server-{{ mongodb_repo_version }}.gpg /tmp/mongodb-server-{{ mongodb_repo_version }}.asc
  args:
    creates: /usr/share/keyrings/mongodb-server-{{ mongodb_repo_version }}.gpg
  become: true

- name: 'Mongodb | Debian | Copy mongo repository template'
  ansible.builtin.template:
    src: mongodb.list.j2
    dest: /etc/apt/sources.list.d/mongodb.list
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Update apt cache

- name: 'Mongodb | Debian | Ensure MongoDB is installed'
  ansible.builtin.apt:
    name: "mongodb-org"
    state: present
    update_cache: true
  become: true
  notify: Update apt cache
