---
- name: 'Mongodb | Debian | Download MongoDB GPG key'
  ansible.builtin.get_url:
    url: https://pgp.mongodb.com/server-{{ mongodb_repo_version }}.asc
    dest: /tmp/mongodb-server-{{ mongodb_repo_version }}.asc
    mode: '0644'
  become: true

- name: 'Mongodb | Debian | Convert MongoDB GPG key to dearmored format'
  ansible.builtin.command: >
    gpg --dearmor -o /usr/share/keyrings/mongodb-server-{{ mongodb_repo_version }}.gpg /tmp/mongodb-server-{{ mongodb_repo_version }}.asc
  args:
    creates: /usr/share/keyrings/mongodb-server-{{ mongodb_repo_version }}.gpg
  become: true

- name: 'Mongodb | Debian | Copy mongo repository template'
  ansible.builtin.template:
    src: mongodb.list.j2
    dest: /etc/apt/sources.list.d/mongodb.list
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Update apt cache

- name: 'Mongodb | Debian | Ensure MongoDB is installed'
  ansible.builtin.apt:
    name: "mongodb-org"
    state: present
    update_cache: true
  become: true
  notify: Update apt cache

- name: 'Mongodb | Debian | AppArmor | Check if AppArmor binary exists'
  ansible.builtin.stat:
    path: /usr/sbin/aa-status
  register: apparmor_binary

- name: 'Core | Security | Debian | AppArmor | Check if AppArmor is installed'
  ansible.builtin.stat:
    path: /etc/apparmor.d
  register: apparmor_dir
  become: true
  when: apparmor_binary.stat.exists

- name: 'Mongodb | Debian | Check if AppArmor is installed'
  ansible.builtin.stat:
    path: /etc/apparmor.d
  register: apparmor_dir
  become: true
  when: apparmor_binary.stat.exists

- name: 'Core | Debian | AppArmor | Set Apparmor is installed'
  ansible.builtin.set_fact:
    apparmor_installed: apparmor_binary.stat.exists and apparmor_dir.stat.exists and apparmor_dir.stat.isdir
  changed_when: false
  failed_when: false

- name: 'Mongodb | Debian | Check if Mongodb is installed'
  ansible.builtin.stat:
    path: /usr/bin/mongod
  register: mongod_exec

- name: 'Mongodb | Debian | Enable apparmor for MongoDB from template'
  ansible.builtin.template:
    src: mongodb.apparmor.j2
    dest: /etc/apparmor.d/usr.bin.mongod
    owner: root
    group: root
    mode: '0644'
  become: true
  when:
    - apparmor_installed is defined
    - apparmor_installed
    - mongod_exec.stat.exists

- name: 'Mongodb | Debian | Parse and load the MongoDB AppArmor profile in complain mode'
  ansible.builtin.command: apparmor_parser -r /etc/apparmor.d/usr.bin.mongod
  changed_when: false
  when:
    - apparmor_installed is defined
    - apparmor_installed
    - mongod_exec.stat.exists

- name: 'Mongodb | Debian | Switch to enforce mode once tested for MongoDB'
  ansible.builtin.command: aa-enforce /usr/bin/mongod
  changed_when: false
  when:
    - apparmor_installed is defined
    - apparmor_installed
    - mongod_exec.stat.exists
    - apparmor_enforce_mode

- name: 'Mongodb | Debian | Switch to complain mode once tested for MongoDB'
  ansible.builtin.command: aa-complain /usr/bin/mongod
  changed_when: false
  when:
    - apparmor_installed is defined
    - apparmor_installed
    - mongod_exec.stat.exists
    - not apparmor_enforce_mode
