# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == debian_family_name

# MongoDB
- name: Create MongoDB keyfile
  ansible.builtin.copy:
    content: "{{ mongodb_keyfile_content }}"
    dest: "{{ mongodb_keyfile }}"
    owner: mongodb
    group: mongodb
    mode: "0600"
  become: true
  notify: Restart MongoDB

- name: Configure MongoDB
  ansible.builtin.template:
    src: mongodb.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart MongoDB

- name: Ensure MongoDB is started and enabled
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    state: started
  become: true

- name: Enable apparmor for MongoDB from template
  ansible.builtin.template:
    src: mongodb.apparmor.j2
    dest: /etc/apparmor.d/usr.sbin.mongod
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Parse and load the MongoDB AppArmor profile in complain mode
  ansible.builtin.command: apparmor_parser -r /etc/apparmor.d/usr.bin.mongod
  changed_when: false

- name: Switch to enforce mode once tested for MongoDB
  ansible.builtin.command: aa-enforce /usr/bin/mongod
  changed_when: false
