# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: 'Mongodb | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

# MongoDB
- name: 'Mongodb | Create MongoDB keyfile'
  ansible.builtin.copy:
    content: "{{ mongodb_keyfile_content }}"
    dest: "{{ mongodb_keyfile }}"
    owner: mongodb
    group: mongodb
    mode: "0600"
  become: true
  notify: Restart MongoDB

- name: 'Mongodb | Ensure mongodb user exists (if not using a package manager)'
  ansible.builtin.user:
    name: mongodb
    system: true
    shell: /usr/sbin/nologin
  become: true

- name: 'Mongodb | Configure MongoDB'
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongodb
    group: mongodb
    mode: "0644"
  become: true
  notify: Restart MongoDB

- name: 'Mongodb | Ensure MongoDB is started and enabled'
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    state: started
  become: true

#- name: 'Mongodb | Initialize MongoDB replica set if needed'
#  ansible.builtin.command: mongosh --quiet --eval 'rs.initiate()'
#  register: rs_init
#  failed_when: rs_init.rc != 0 and "'already initialized'" not in rs_init.stdout
#  changed_when: false
#  when: mongodb_authorization == 'enabled'
#  notify: Restart MongoDB

- name: 'Mongodb | Allow MongoDB access from trusted host'
  community.general.ufw:
    rule: allow
    port: "{{ mongodb_port | default(27017) }}"
    proto: tcp
    from_ip: "{{ mongodb_bind_ip | default('127.0.0.1') }}"
  become: true
