# SPDX-License-Identifier: MIT-0
---
# defaults file for install_network_tools
network_tools_ufw_rules:
  - { port: '5201', proto: 'tcp', comment: 'iperf3 server' }
  - { port: '5201', proto: 'udp', comment: 'iperf3 UDP testing' }
  - { port: '8080', proto: 'tcp', comment: 'Wireshark remote capture' }
  - { port: '53', proto: 'udp', comment: 'DNS client queries' }

# Tools that need special AppArmor permissions
network_tools_apparmor_profiles:
  - wireshark
  - nmap
  - traceroute
  - tcpdump
