# roles/libvirt/defaults/main.yml
---
libvirt_tcp_port: 16509
libvirt_tls_port: 16514
spice_port_range: "5900:5999"
migration_port_range: "49152:49215"

# UFW rules for libvirt
libvirt_ufw_rules:
  - { port: "{{ libvirt_tcp_port }}", proto: 'tcp', comment: 'Libvirt TCP connections' }
  - { port: "{{ libvirt_tls_port }}", proto: 'tcp', comment: 'Libvirt TLS connections' }
  - { port: "{{ spice_port_range }}", proto: 'tcp', comment: 'SPICE client connections' }
  - { port: "{{ migration_port_range }}", proto: 'tcp', comment: 'VM migration ports' }
