# SPDX-License-Identifier: MIT-0
---
fleet_server_es_version: '8.x'
fleet_server_kibana_host: 'https://localhost:5601'
fleet_server_elasticsearch_host: 'https://localhost:9200'
fleet_server_certs_path: '/etc/elasticsearch/certs'
