---
- name: 'Graylog | Debian | Download Graylog repository package'
  ansible.builtin.get_url:
    url: https://packages.graylog2.org/repo/packages/{{ graylog_repo_version }}.deb
    dest: /tmp/graylog_server_package.deb
    mode: "0644"
    owner: root
    group: root
  become: true

- name: 'Graylog | Debian | Install Graylog repository package'
  ansible.builtin.command:
    cmd: dpkg -i /tmp/graylog_server_package.deb
  register: dpkg_result
  changed_when: dpkg_result.stdout is defined and dpkg_result.stdout != "" and not dpkg_result.stdout is search("already installed")
  become: true

- name: 'Graylog | Debian | Install Graylog server'
  ansible.builtin.apt:
    name:
      - graylog-server
      - graylog-datanode
    state: present
    update_cache: true
  become: true

- name: 'Graylog | Debian | Mark Graylog server package as held'
  ansible.builtin.command:
    cmd: apt-mark hold graylog-server
  register: apt_mark_result
  changed_when: apt_mark_result.stdout is defined and apt_mark_result.stdout != "" and not apt_mark_result.stdout is search("was already set on hold")
  become: true
