# roles/qemu/tasks/debian.yml
---
- name: 'Crowdsec | Debian | Add CrowdSec repository key'
  ansible.builtin.apt_key:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    state: present

- name: 'Crowdsec | Debian | Add CrowdSec repository'
  ansible.builtin.apt_repository:
    repo: deb https://packagecloud.io/crowdsec/crowdsec/debian/ bookworm main
    state: present

- name: 'Crowdsec | Debian | Install crowdsec package'
  ansible.builtin.apt:
    name: crowdsec
    state: present

- name: 'Crowdsec | Debian | Install crowdsec-firewall-bouncer-nftables'
  ansible.builtin.apt:
    name: crowdsec-firewall-bouncer-nftables
    state: present
