# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: 'Crowdsec | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'Crowdsec | Include install tasks'
  ansible.builtin.include_tasks: install.yml

- name: 'Crowdsec | Include configure tasks'
  ansible.builtin.include_tasks: configure.yml

- name: 'Crowdsec | Install collections'
  ansible.builtin.include_tasks: collections.yml

- name: 'Crowdsec | Install parsers'
  ansible.builtin.include_tasks: parsers.yml

- name: 'Crowdsec | Install scenarios'
  ansible.builtin.include_tasks: scenarios.yml

- name: 'Crowdsec | Install bouncers'
  ansible.builtin.include_tasks: bouncers.yml

- name: 'Crowdsec | Install WAF'
  when: crowdsec_install_waf
  ansible.builtin.include_tasks: waf.yml
