---
- name: Install ModSecurity and dependencies
  ansible.builtin.apt:
    name:
      - libapache2-mod-security2
      - apache2
    state: present

- name: Enable ModSecurity module
  ansible.builtin.shell: |
    a2enmod security2
  args:
    executable: /bin/bash

- name: Enable default OWASP CRS (optional - improve security)
  ansible.builtin.copy:
    src: /usr/share/modsecurity-crs/base_rules/
    dest: /etc/modsecurity/
    remote_src: true
  ignore_errors: true

- name: Restart Apache2 to apply ModSecurity changes
  ansible.builtin.service:
    name: apache2
    state: restarted