- name: 'Core | Handlers | Security | Debian | AppArmor | Reload apparmor profiles'
  ansible.builtin.command:
    cmd: aa-enforce /etc/apparmor.d/*
  become: true
  changed_when: false
  register: apparmor_enforce
  failed_when: apparmor_enforce.rc != 0 and "No such file or directory" not in apparmor_enforce.stderr
  when: apparmor_installed

- name: 'Core | Handlers | Security | Debian | AppArmor | Load AppArmor profile'
  ansible.builtin.command: "apparmor_parser -r /etc/apparmor.d/{{ apparmor_profile }}"
  become: true
  changed_when: false
  register: apparmor_reload
  failed_when: apparmor_reload.rc != 0 and 'No such file or directory' not in apparmor_reload.stderr
  when: apparmor_installed

- name: 'Core | Handlers | Security | Debian | AppArmor | Load multiple custom AppArmor profiles'
  ansible.builtin.command: "apparmor_parser -r /etc/apparmor.d/{{ item }}"
  loop: "{{ apparmor_custom_profile | map(attribute='profile') | list }}"
  become: true
  changed_when: false
  register: apparmor_reload
  failed_when: apparmor_reload.rc != 0 and 'No such file or directory' not in apparmor_reload.stderr
  when: apparmor_installed

- name: 'Core | Handlers | Security | Debian | AppArmor | Get apparmor status'
  ansible.builtin.command: aa-status
  register: aa_status
  changed_when: false
  when: apparmor_installed
