- name: Create fail2ban jail.local from template
  ansible.builtin.template:
    src: common/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart fail2ban

- name: Check if Fail2ban binary exists
  ansible.builtin.stat:
    path: /usr/bin/fail2ban-client
  register: fail2ban_binary

- name: Set fail2ban exists variable
  ansible.builtin.set_fact:
    fail2ban_exists: fail2ban_binary.stat.exists
  changed_when: false
  failed_when: false

- name: Ensure Fail2ban service is enabled and started
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
  become: true
  when: fail2ban_exists
