---
- name: 'Core | Security | Include security vars'
  ansible.builtin.include_vars: "{{ role_path }}/vars/security/main.yml"

- name: 'Core | Security | Include all OS security tasks'
  ansible.builtin.include_tasks: "{{ item }}"
  with_fileglob:
    - "security/{{ ansible_os_family | lower }}/*.yml"
  register: security_debian_tasks

- name: 'Core | Security | Include UFW Security tasks'
  ansible.builtin.include_tasks: "ufw.yml"

- name: 'Core | Security | Include Fail2ban Security tasks'
  ansible.builtin.include_tasks: "fail2ban.yml"
