---
- name: Include security vars
  ansible.builtin.include_vars: "{{ role_path }}/vars/security/main.yml"

- name: Include all Debian security tasks
  include_tasks: "{{ item }}"
  with_fileglob:
    - security/debian/*.yml
  register: security_debian_tasks
  when: ansible_os_family == debian_family_name

- name: Include UFW Security tasks
  ansible.builtin.include_tasks: "ufw.yml"

- name: Include Fail2ban Security tasks
  ansible.builtin.include_tasks: "fail2ban.yml"
