---
virtualization_libvirt_tcp_port: 16509
virtualization_libvirt_tls_port: 16514
virtualization_spice_port_range: "5900:5999"
virtualization_migration_port_range: "49152:49215"

# UFW rules for libvirt
virtualization_libvirt_ufw_rules:
  - { port: "{{ virtualization_libvirt_tcp_port }}", proto: "tcp", comment: "Libvirt TCP connections" }
  - { port: "{{ virtualization_libvirt_tls_port }}", proto: "tcp", comment: "Libvirt TLS connections" }
  - { port: "{{ virtualization_spice_port_range }}", proto: "tcp", comment: "SPICE client connections" }
  - { port: "{{ virtualization_migration_port_range }}", proto: "tcp", comment: "VM migration ports" }

virtualization_libvirt_network_ipv4_address: "{{ host_ipv4_addr }}/24"
virtualization_libvirt_network_ipv4_gw: "{{ host_ipv4_gw }}"
virtualization_libvirt_network_ipv4_dns: "{{ default_dns | join(',') }}"
virtualization_libvirt_network_ipv4_type: manual
virtualization_libvirt_storage_pool_name: default
virtualization_libvirt_storage_pool_path: /mnt/storage/libvirt
virtualization_apparmor_profiles:
  - usr.sbin.libvirtd
  - usr.lib.libvirt.virt-aa-helper
  - usr.bin.qemu-system-x86_64
