---
- name: Setup ACG server
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: common
    - role: core
    - role: gde_remove
    - role: archive_tools
    - role: development_tools
    - role: network_tools
    - role: diagnostic_tools
    - role: hashicorp
    - role: virtualization
    - role: mongodb
    - role: opensearch
    - role: graylog
