---
- name: Setup pCloud Debian server
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - '../../group_vars/all.yml'
    - '../../group_vars/vault.yml'
  vars:
    core_install_nvidia: false
    containers_install_docker: false
    graylog_master_node_server: '127.0.0.1:12201'
    graylog_http_external_uri: 'https://sl2rd15ecd4125.pcloud.axway.int:12201'
    wazuh_install_agent: true
  roles:
    - role: common
#    - role: core
#      core_ufw_allowed_sources:
#        - "10.134.128.180/16"
#    - role: gde_remove
#    - role: development_tools
#    - role: hashicorp
##    - role: virtualization
#    - role: containers
#    - role: mongodb
#    - role: opensearch
    - role: graylog
#    - role: wazuh
#    - role: trivy
#    - role: falco
#    - role: crowdsec
#    - role: netdata
#    - role: grafana
#    - role: elasticsearch
#    - role: kibana
#    - role: fleet_server
#    - role: checkmk