- name: 'Core | Network Tools | Debian | Install network tools'
  ansible.builtin.apt:
    name:
      - nmap
      - dnsutils
      - wireshark
      - speedtest-cli
      - curl
      - wget
      - iptables
      - iputils-ping
      - traceroute
      - dnsutils
    state: present
    update_cache: true
  become: true
