# SPDX-License-Identifier: MIT-0
---
# tasks file for install_network_tools
- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == debian_family_name

- name: Include security vars
  ansible.builtin.include_vars: "{{ role_path }}/vars/security/main.yml"

- name: Configure UFW rules for network tools
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  with_items: "{{ network_tools_ufw_rules }}"
  become: true
  when: ufw_installed
  notify: Reload UFW

- name: Configure AppArmor profiles for network tools
  ansible.builtin.template:
    src: network_tools/network_tool_apparmor.j2
    dest: "/etc/apparmor.d/local/usr.bin.{{ item }}"
    mode: '0644'
  with_items: "{{ network_tools_apparmor_profiles }}"
  become: true
  when:
    - apparmor_installed is defined
    - apparmor_installed
  notify: Reload AppArmor profiles
