---
- name: Install AppArmor packages
  ansible.builtin.apt:
    name:
      - apparmor
      - apparmor-utils
      - apparmor-profiles
      - apparmor-profiles-extra
    state: present
    update_cache: true
  become: true

- name: Check if AppArmor is installed
  ansible.builtin.stat:
    path: /etc/apparmor.d
  register: apparmor_dir
  become: true

- name: Ensure AppArmor service is enabled and started
  ansible.builtin.systemd:
    name: apparmor
    state: started
    enabled: true
  register: apparmor_installed
  become: true
  notify: Reload apparmor profiles

- name: Update kernel boot parameters for AppArmor
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((?!apparmor=1|security=apparmor).)*"$'
    line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} apparmor=1 security=apparmor"'
    backrefs: true
  become: true
  notify: Update grub
