- name: Install libvirt
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system-systemd
      - libvirt-daemon-config-network
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-driver-lxc
      - libvirt-daemon-driver-storage-iscsi-direct
      - libvirt-daemon-driver-vbox
      - libvirt-login-shell
      - libvirt-wireshark
    state: present
    notify: Update apt cache

- name: Install Vagrant
  ansible.builtin.apt:
    name:
      - vagrant
      - vagrant-libvirt
    state: present
    when: { { install_vagrant } }
    notify: Update apt cache

- name: Install LXC
  ansible.builtin.apt:
    name:
      - lxc
      - lxc-templates
      - lxcfs
      - lxctl
    state: present
    when: { { install_lxc } }
    notify: Update apt cache

- name: Install LXD
  ansible.builtin.apt:
    name:
      - lxd
      - lxd-tools
      - lxd-agent
      - lxd-client
      - lxd-migrate
    state: present
    when: { { install_lxd } }
    notify: Update apt cache
