# SPDX-License-Identifier: MIT-0
---
# handlers file for wazuh
- name: 'Restart wazuh-dashboard'
  ansible.builtin.systemd:
    name: wazuh-dashboard
    state: restarted

- name: 'Restart wazuh-server'
  ansible.builtin.systemd:
    name: wazuh-server
    state: restarted

- name: 'Enable wazuh-server password enrollment'
  block:
    - name: 'Enable password in ossec.conf'
      ansible.builtin.lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '^<use_password>'
        line: "<use_password>\"{{ wazuh_reg_password }}\"</use_password>"
        create: true
        mode: '0644'
        owner: root
        group: wazuh

    - name: 'Add password in a file'
      ansible.builtin.copy:
        dest: /var/ossec/etc/authd.pass
        content: "{{ wazuh_reg_password }}"
        mode: "0644"
        owner: root
        group: wazuh
