---
- name: 'Kibana | Certs | Ensure certs directory exists'
  ansible.builtin.file:
    path: '{{ kibana_certs_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: 'Kibana | Certs | Generate CA private key (only if not exists)'
  community.crypto.openssl_privatekey:
    path: '{{ kibana_certs_path }}/ca.key'
  when: not lookup('ansible.builtin.file', kibana_certs_path + '/ca.key', errors='ignore')

- name: 'Kibana | Certs | Generate CA certificate (only if not exists)'
  community.crypto.x509_certificate:
    path: '{{ kibana_certs_path }}/ca.crt'
    privatekey_path: '{{ kibana_certs_path }}/ca.key'
    provider: selfsigned
    selfsigned_not_after: '+3650d'
  when: not lookup('ansible.builtin.file', kibana_certs_path + '/ca.crt', errors='ignore')

- name: 'Kibana | Certs | Generate Kibana private key'
  community.crypto.openssl_privatekey:
    path: '{{ kibana_certs_path }}/kibana.key'

- name: 'Kibana | Certs | Generate Kibana CSR'
  community.crypto.openssl_csr:
    path: '{{ kibana_certs_path }}/kibana.csr'
    privatekey_path: '{{ kibana_certs_path }}/kibana.key'
    common_name: 'kibana'

- name: 'Kibana | Certs | Sign Kibana certificate'
  community.crypto.x509_certificate:
    path: '{{ kibana_certs_path }}/kibana.crt'
    csr_path: '{{ kibana_certs_path }}/kibana.csr'
    ownca_path: '{{ kibana_certs_path }}/ca.crt'
    ownca_privatekey_path: '{{ kibana_certs_path }}/ca.key'
    provider: ownca
    ownca_not_after: '+3650d'
