# roles/qemu/tasks/debian.yml
---
- name: 'Kibana | Debian | Install Python crypto libraries'
  ansible.builtin.apt:
    name:
      - python3-cryptography
      - python3-openssl
    state: present
  become: true
  notify: 'Update apt cache'

- name: 'Kibana | Debian | Add Elastic GPG Key'
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: 'Kibana | Debian | Add Elastic APT repository'
  ansible.builtin.apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/8.x/apt stable main'
    state: present
    filename: "{{ kibana_repo_filename }}"

- name: 'Kibana | Debian | Install Kibana'
  ansible.builtin.apt:
    name: kibana
    state: present
  notify: 'Update apt cache'
