# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: 'Kibana | Include OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'Kibana | Generate Kibana certificates'
  ansible.builtin.include_tasks: certs.yml

- name: 'Kibana | Configure Kibana'
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: '0640'
  notify: Restart Kibana

- name: 'Kibana | Ensure Kibana service is enabled and started'
  ansible.builtin.service:
    name: kibana
    enabled: true
    state: started
