# SPDX-License-Identifier: MIT-0
---
# tasks file for lxd
- name: Include LXD Debian-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Include LXD vars
  ansible.builtin.include_vars: "{{ role_path }}/vars/lxd.yml"

- name: Configure UFW rules for LXD
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ lxd_network_ports }}"
  become: true
  when: ufw_installed
  notify: Reload UFW

- name: Allow traffic from LXD managed bridge network
  community.general.ufw:
    rule: allow
    from: lxd_subnet
  become: true
  when: ufw_installed
  notify: Reload UFW

- name: Start and enable LXD service
  ansible.builtin.systemd:
    name: lxd
    state: started
    enabled: true
  when: install_lxd
  become: true
