# SPDX-License-Identifier: MIT-0
---
# tasks file for lxd
- name: 'Virtualization | LXD | Include LXD OS-specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'Virtualization | LXD | Include LXD vars'
  ansible.builtin.include_vars: "{{ role_path }}/vars/lxd.yml"

- name: 'Virtualization | LXD | Configure UFW rules for LXD'
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ virtualization_lxd_network_ports }}"
  become: true
  when: ufw_installed
  notify: Reload UFW

- name: 'Virtualization | LXD | Allow traffic from LXD managed bridge network'
  community.general.ufw:
    rule: allow
    from: "{{ virtualization_lxd_subnet }}"
  become: true
  when: ufw_installed
  notify: Reload UFW

- name: 'Virtualization | LXD | Start and enable LXD service'
  ansible.builtin.systemd:
    name: lxd
    state: started
    enabled: true
  when: install_lxd
  become: true
