---
- name: 'OpenSearch | Debian | Include core debian handlers'
  ansible.builtin.include_tasks: "{{ role_path }}/../common/handlers/debian.yml"

- name: "OpenSearch | Debian | Check if OpenSearch GPG exists"
  ansible.builtin.stat:
    path: /usr/share/keyrings/opensearch.gpg
  register: opensearch_gpg
  changed_when: false

- name: "OpenSearch | Debian | Download Opensearch GPG key"
  ansible.builtin.get_url:
    url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
    dest: /tmp/opensearch-key.gpg
    mode: "0644"
  become: true
  when: not opensearch_gpg.stat.exists

- name: "OpenSearch | Debian | Import OpenSearch GPG key"
  ansible.builtin.command: >
    gpg --dearmor --batch --yes -o /usr/share/keyrings/opensearch.gpg /tmp/opensearch-key.gpg
  args:
    creates: /usr/share/keyrings/opensearch.gpg
  become: true
  when: not opensearch_gpg.stat.exists

- name: "OpenSearch | Debian | Set permissions for OpenSearch GPG keyring"
  ansible.builtin.file:
    path: /usr/share/keyrings/opensearch.gpg
    mode: "0644"
  become: true
  when: not opensearch_gpg.stat.exists

- name: "OpenSearch | Debian | Check if OpenSearch repo exists"
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/opensearch.list
  register: opensearch_repo
  changed_when: false

- name: "OpenSearch | Debian | Copy opensearch repository template"
  ansible.builtin.template:
    src: opensearch.list.j2
    dest: /etc/apt/sources.list.d/opensearch.list
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Update apt cache
  when: not opensearch_repo.stat.exists

- name: "OpenSearch | Debian | Copy opensearch repository template"
  ansible.builtin.template:
    src: opensearch-dashboards.list.j2
    dest: /etc/apt/sources.list.d/opensearch-dashboards.list
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Update apt cache
  when: not opensearch_repo.stat.exists

- name: "OpenSearch | Debian | Ensure OpenSearch and OpenSearch Dashboard is installed"
  ansible.builtin.apt:
    name:
      - opensearch
    state: present
    update_cache: true
  environment:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_admin_password }}"
  become: true
  when: not opensearch_binary.stat.exists

- name: "OpenSearch | Debian | Re-check if OpenSearch is now installed"
  ansible.builtin.stat:
    path: /usr/share/opensearch/bin/opensearch
  register: opensearch_binary

- name: "OpenSearch | Debian | Check if AppArmor profile for OpenSearch exists"
  ansible.builtin.command: aa-status
  register: aa_status
  changed_when: false

- name: "OpenSearch | Debian | Set if opensearch apparmor is applied"
  ansible.builtin.set_fact:
    aa_opensearch_installed: "'/usr/share/opensearch/bin/opensearch' in aa_status.stdout"
  changed_when: false

- name: "OpenSearch | Debian | Set if opensearch apparmor should be applied"
  ansible.builtin.set_fact:
    aa_should_apply: (not aa_opensearch_installed and opensearch_binary.stat.exists and aa_status.stat.exists)
  changed_when: false

- name: "OpenSearch | Debian | Enable apparmor for OpenSearch from template"
  ansible.builtin.template:
    src: opensearch.apparmor.j2
    dest: /etc/apparmor.d/usr.sbin.opensearch
    owner: root
    group: root
    mode: "0644"
  become: true
  when: aa_should_apply

- name: "OpenSearch | Debian | Parse and load the OpenSearch AppArmor profile in complain mode"
  ansible.builtin.command: apparmor_parser -r /etc/apparmor.d/usr.sbin.opensearch
  when: aa_should_apply

- name: "OpenSearch | Debian | Switch to enforce mode once tested for OpenSearch"
  ansible.builtin.command: aa-enforce /usr/bin/opensearch
  when:
    - aa_should_apply
    - apparmor_enforce_mode

- name: "OpenSearch | Debian | Switch to enforce mode once tested for OpenSearch"
  ansible.builtin.command: aa-complain /usr/bin/opensearch
  when:
    - aa_should_apply
    - not apparmor_enforce_mode

