---
core_nvidia_ufw_rules:
  - port: 5000
    proto: tcp
    comment: "NVIDIA NVML exporter"
  - port: 9835
    proto: tcp
    comment: "NVIDIA DCGM exporter"

# AppArmor profiles for NVIDIA binaries
core_nvidia_apparmor_profiles:
  - nvidia-smi
  - nvidia-settings
  - nvidia-xconfig
