---
- name: 'Containers | Docker | Include Debian tasks'
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: 'Containers | Docker | Ensure Docker service is enabled and started'
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  become: true
  when: docker_binary.stat.exists

- name: 'Containers | Docker | Login to Docker registry'
  community.docker.docker_login:
    registry_url: "{{ docker.registry }}"
    username: "{{ docker.username }}"
    password: "{{ docker.password }}"
  become: true
  when:
    - docker_binary.stat.exists
    - docker.username != ''
    - docker.password != ''

- name: 'Containers | Docker | Apply UFW rules'
  ansible.builtin.include_tasks: "ufw.yml"
  when: docker_binary.stat.exists and containers_docker_ports | length > 0

- name: 'Containers| Docker | Include Docker container configurations'
  ansible.builtin.include_tasks: "docker_containers.yml"
  when: docker_binary.stat.exists
