# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role_template
- name: 'Virtualization | Include Libvirt tasks'
  ansible.builtin.include_tasks: "libvirt/main.yml"
  when: virtualization_install_libvirt

- name: 'Virtualization | Include LXC tasks'
  ansible.builtin.include_tasks: "lxc/main.yml"
  when: virtualization_install_lxc

- name: 'Virtualization | Include LXD tasks'
  ansible.builtin.include_tasks: "lxd/main.yml"
  when: virtualization_install_lxd

- name: 'Virtualization | Include Vagrant tasks'
  ansible.builtin.include_tasks: "vagrant/main.yml"
  when: virtualization_install_vagrant
